// app/api/captures/route.ts
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth";
import { parseFile } from "@/lib/parser/unstructured";
import { extractKnowledge } from "@/lib/ai/extract";

export async function POST(req: Request) {
    try {
        const session = await getSession();

        if (!session) {
            return NextResponse.json({ error: "Unauthorized: Please log in first" }, { status: 401 });
        }

        const formData = await req.formData();
        const text = formData.get("text") as string;
        const files = formData.getAll("files") as File[];
        let extractedText = text;

        console.log("Files:", files.length);
        console.log("Before parse");

        if (files.length > 0) {
            extractedText += "\n" + await parseFile(files[0]);
        }

        console.log("After parse");
        console.log(extractedText.slice(0, 300));

        console.log("Before AI");
        const knowledge = await extractKnowledge(extractedText);
        console.log("After AI");

        // You can use 'text' and 'files' directly here
        // Example:
        const capture = await prisma.capture.create({
            data: {
                text: extractedText,
                userId: session.user.id,
                createdAt: new Date(),
            },
        });

        //saving knowlege ntry generated by ai
        console.log(knowledge)
        const knowledgeEntry = await prisma.knowledgeEntry.create({
            data: {
                title: knowledge.title,
                content: knowledge.markdown,
                userId: session.user.id,
                topicId: null,

            },
        });

        return NextResponse.json({ success: true, knowledgeEntry });
    } catch (error: any) {
        console.error("Failed to create capture:", error);
        return NextResponse.json(
            { error: error?.message || "Failed to save capture" },
            { status: 500 }
        );
    }
}

